### ISSUE TITLE
A typo on paper? the center frame for only the 1 4 and 9 frame. (1 5 9 ) ?

### ISSUE THREAD

**Issue by yunfanLu** [sichun233746/MoTIF#2]
I believe I have come across a potential typo in your paper, specifically within the training dataset details provided in Section 4. The center is mentioned as 1 4 9, which has caused confusion. This could be attributed to your reference to the description in VideoINR. Kindly verify whether the correct sequence is 1 5 9 or 1 4 9.

Reference: https://github.com/Picsart-AI-Research/VideoINR-Continuous-Space-Time-Super-Resolution/issues/17

**Comment by sichun233746** [comment]
Yes, this is a typo. We use the exact same setting as VideoINR. Thanks for identifying this. We will correct it.
