### ISSUE TITLE
Evaluation metrics on Y channels

### ISSUE THREAD

**Issue by Joseph-LIN-Tech** [sichun233746/MoTIF#3]
Thank you for your great work. 
Regarding the test part, I have a question: are the PSNR and SSIM metrics in the paper obtained on the Y channel? 
Looking forward to your rely~

**Comment by sichun233746** [comment]
@lgx-tech Yes, all the PSNR and SSIM numbers are measured on the Y channel.
This is the exact same evaluation method as the STVSR previous works.

**Comment by Joseph-LIN-Tech** [comment]
Thanks for your response~
