### ISSUE TITLE
Where to get the pre-trained weight?

### ISSUE THREAD

**Issue by hahazh** [sichun233746/MoTIF#4]
Hello! I tried to click this:
## Pre-trained weights
[best.pth](https://sichun233746.github.io/MoTIF/)
but it refers to your project page.
 and also,  "saved_checkpoints/best.pth" is not a valid pretrained weight format in pytorch, I wonder where to get the real pretrained model?

**Comment by sichun233746** [comment]
@hahazh Sorry for your troubles.
I must have pasted the wrong link. Now it's fixed.
Thank you for asking!

**Comment by hahazh** [comment]
Thanks for your reply, there is another question:
in models/modules/Ours.py
I noticed the following code:
        # ckpt = torch.load("/home/abcd233746pc/0801/raft_smooth_0728_iter12.pth")['model']
        # keys = list(ckpt.keys())
        # for key in keys:
        #     tmp = key.replace("flow_predictor.", "")
        #     ckpt[tmp] = ckpt[key]
        #     del ckpt[key]
        # self.flow_predictor.load_state_dict(ckpt, strict=True)
  Is the weight of raft (raft_smooth_0728_iter12.pth) necessary? Or, I can directly use your best.pth, including the weight of flownet raft.

**Comment by hahazh** [comment]
I have currently tried to replicate your results with a pre-trained model. At present, although the whole process has been completed and the pictures with normal visual effects have been output, I cannot achieve time modulation by adjusting the middle time $t$.
All the intermediate moments are the same as the first frame (I_0), with no adjustment of motion. I think I must get something wrong (e.g. failed to load optical flow weights correctly). It may be that you are in a hurry and the current code is difficult to follow, even for more experienced researchers. (I am very familiar with the VideoINR and TMNet, Zooming SlowMo) 
Based on these considerations, Could you consider simply giving out a demo.py so that researchers can follow your work easily?
For example, the input is two LR images, along with the desired intermediate moments and resolution, and then the demo.py can directly output the super-revolved SR.
Thank you again for your excellent work and apologize for my possibly abrupt request.

**Comment by sichun233746** [comment]
Hi @hahazh,
For your two questions.
1.Aboout the model weight:
Only best.pth is needed.
2.About the code:
I will definitely release a readable and correct code in the future. This version is only for those who are urgent to reproduce the results.
Please allowed me clarify that the problem your are facing right now is that all the motion turned out to be 0 and can't get the exact result.

**Comment by hahazh** [comment]
Thank you for your prompt response! I'm sorry, but I would like to clarify one question: Is "all the motion turned out to be 0" a problem in my reproduction or is it a bug in your current code? If it's the former, I will continue trying to modify the code (such as visualizing intermediate optical flow, etc.). If it's the latter, I will wait for further fixes from you. Thank you again! my code is some like this:


```
def single_forward(model, imgs_in, space_scale, time_scale):

       
    target_t = []
    for i in range(time_scale):
        target_t.append(torch.tensor([i / time_scale]).cuda())
    # print(target_t)
    with torch.no_grad():
        b, n, c, h, w = imgs_in.size()
        h_n = int(4 * np.ceil(h / 4))
        w_n = int(4 * np.ceil(w / 4))
        imgs_temp = imgs_in.new_zeros(b, n, c, h_n, w_n).cuda()
        imgs_temp[:, :, :, 0:h, 0:w] = imgs_in
        # print('img in shape')
        # print(imgs_temp.shape)
        model_output,_,_ = model.netG(imgs_temp,None,target_t,space_scale)
        model_output = model_output[:,:,:,:h*4,:w*4]
        model_output = model_output.squeeze(0)
        # print('out img',model_output.shape)
    
    return model_output

```

**Comment by sichun233746** [comment]
@hahazh Do you get the PSNR numbers?

**Comment by hahazh** [comment]
Hello, I tested the PSNR on Vid4,
total PSNR 25.780266666633782
total SSIM 0.7750187010777306
The results look almost identical to what you reported in your paper. I believe I have successfully reproduced your results, and I also noticed significant motion in the intermediate frames.

Additionally, could you provide me with the specific environment you used for running the experiments? For example, the version of the NVIDIA graphics card, CUDA, and Torch. I haven't been able to compile the DCN module on my 3090, most likely due to version compatibility issues. Currently, I can only input lower-resolution LR images on my 1080ti. When testing with Adobe (four times downsampling), I encountered an "out of memory" error. Thank you once again for your response.

**Comment by sichun233746** [comment]
Hi @hahazh,

Here are the environment variables you asked for:
python: 3.6.10
pytorch: 1.8.0
cuda: 11.4
GPU: Nvidia V100
Sorry for late reply since I'm heading to ICCV2023.

**Comment by hahazh** [comment]
Thank you very much, have a good trip!

**Comment by Explore008** [comment]
> 我目前尝试使用预先训练的模型复制您的结果。目前虽然整个过程已经完成，并且输出了具有正常视觉效果的画面，但我无法通过调整中间时间来实现时间调制t.所有中间时刻都与第一帧（I_0）相同，没有调整运动。我想我一定弄错了什么（例如，未能正确加载光流砝码）。可能是您很着急，即使对于更有经验的研究人员，当前的代码也很难遵循。（我非常熟悉VideoINR和TMNet，Zooming SlowMo）基于这些考虑，您是否可以考虑简单地发布一个 demo.py，以便研究人员可以轻松跟踪您的工作？例如，输入是两个LR图像，以及所需的中间时刻和分辨率，然后 demo.py 可以直接输出超旋转SR。 再次感谢您的出色工作，并为我可能突然的请求道歉。

Hello! How did you realize the model? After I solved the problem of missing DCN_sep method in DCNv2, an alt_cuda_corr file was missing in models/core. Where is this file? Thank you!

**Comment by hahazh** [comment]
> > 我目前尝试使用预先训练的模型复制您的结果。目前虽然整个过程已经完成，并且输出了具有正常视觉效果的画面，但我无法通过调整中间时间来实现时间调制t.所有中间时刻都与第一帧（I_0）相同，没有调整运动。我想我一定弄错了什么（例如，未能正确加载光流砝码）。可能是您很着急，即使对于更有经验的研究人员，当前的代码也很难遵循。（我非常熟悉VideoINR和TMNet，Zooming SlowMo）基于这些考虑，您是否可以考虑简单地发布一个 demo.py，以便研究人员可以轻松跟踪您的工作？例如，输入是两个LR图像，以及所需的中间时刻和分辨率，然后 demo.py 可以直接输出超旋转SR。 再次感谢您的出色工作，并为我可能突然的请求道歉。
> 
> Hello! How did you realize the model? After I solved the problem of missing DCN_sep method in DCNv2, an alt_cuda_corr file was missing in models/core. Where is this file? Thank you!

you may refer to the raft https://github.com/princeton-vl/RAFT, it contains alt_cuda_corr package, you should first compile this.
